# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3142352227a600e3a5fd7e93cd590269ae36a29647add664b45c4530a595b221f8dc95cd4e0527437a0061e0a64e45509d37f33e097b3675d21f006d4a133c8d

test:
  secret_key_base: 0a3e6419df2e1379d5867b6d11b2b2462ee976eb0f3e87db506939e6edc503f7e78e6050e30fdad2b37ca06138e400c5578ab6f6901692c43371d5f84c427be5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
